name: Deploy to WordPress

on:
  push:
    branches: [ main ]
    paths: [ 'content/**' ]
  
  pull_request:
    branches: [ main ]
    paths: [ 'content/**' ]
    types: [ closed ]

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests python-wordpress-xmlrpc markdown beautifulsoup4
        
    - name: Deploy to WordPress
      env:
        WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
        WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
        WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
      run: |
        python3 scripts/deploy_to_wordpress.py
        
    - name: Notify completion
      if: success()
      run: |
        echo "✅ WordPress deployment completed successfully"
        
    - name: Notify failure
      if: failure()
      run: |
        echo "❌ WordPress deployment failed" 